export =[
  {
    name: 'Everton',
    nick_name: 'The Toffees',
    coach: 'Marco Silva',
    website: 'https://www.evertonfc.com',
    founded: 1883,
    stadium_name: 'Goodison Park',
    wins: 3,
    losses: 7,
    goals: 5,
    stadium_capacity: '39,572',
  },
  {
    name: 'Aston Villa',
    nick_name: 'The Villans',
    coach: 'John Terry',
    website: 'https://www.astonvillafc.com',
    founded: 1874,
    stadium_name: 'Villa Park',
    wins: 1,
    losses: 9,
    goals: 2,
    stadium_capacity: '42,682',
  },
  {
    name: 'Chelsea',
    nick_name: 'The Blues',
    coach: 'Frank Lampard',
    website: 'https://www.chelseafc.com',
    founded: 1876,
    stadium_name: 'Stamford Bridge',
    wins: 6,
    losses: 4,
    goals: 19,
    stadium_capacity: '41,798',
  },
  {
    name: 'Manchester City',
    nick_name: 'The Cityzens',
    coach: 'Pep Guardiola',
    website: 'https://www.mancityfc.com',
    founded: 1978,
    stadium_name: 'Etihad',
    wins: 8,
    losses: 2,
    goals: 36,
    stadium_capacity: '48,000',
  },
  {
    name: 'Arsenal',
    nick_name: 'The Gunners',
    coach: 'Unai Emery',
    website: 'https://www.arsenalfc.com',
    founded: 1886,
    stadium_name: 'Emirates',
    wins: 5,
    losses: 5,
    goals: 15,
    stadium_capacity: '60,704',
  },
  {
    name: 'Liverpool',
    nick_name: 'The Reds',
    coach: 'Jurgen Klopp',
    website: 'https://www.liverpoolfc.com',
    founded: 1892,
    stadium_name: 'Anfield',
    wins: 10,
    losses: 0,
    goals: 29,
    stadium_capacity: '54,074',
  },
  {
    name: 'Leicester city',
    nick_name: 'The Foxes',
    coach: 'Brendan Rodgers',
    website: 'https://www.leicesterfc.com',
    founded: 1948,
    stadium_name: 'King Power',
    wins: 4,
    losses: 6,
    goals: 11,
    stadium_capacity: '32,312',
  },
  {
    name: 'Manchester United',
    nick_name: 'The Red Devils',
    coach: 'Ole Gunnar Solskjaer',
    website: 'https://www.manutdfc.com',
    founded: 1886,
    stadium_name: 'Old Trafford',
    wins: 2,
    losses: 8,
    goals: 7,
    stadium_capacity: '59,000',
  },
  {
    name: 'Bournemouth',
    nick_name: 'The Cherriers',
    coach: 'Eddie Howe',
    website: 'https://www.bournemouthfc.com',
    founded: 1980,
    stadium_name: 'Dean Court',
    wins: 5,
    losses: 5,
    goals: 17,
    stadium_capacity: '33,000',
  },
  {
    name: 'Burnley',
    nick_name: 'The Burners',
    coach: 'Sean Dyche',
    website: 'https://www.burnleyfc.com',
    founded: 1898,
    stadium_name: 'Burrow Ground',
    wins: 6,
    losses: 4,
    goals: 8,
    stadium_capacity: '30,043',
  },
  {
    name: 'Tottenham Hotspurs',
    nick_name: 'The Spurs',
    coach: 'Maruicio Pochettino',
    website: 'https://www.tottenhamfc.com',
    founded: 1887,
    stadium_name: 'Spurs',
    wins: 6,
    losses: 4,
    goals: 16,
    stadium_capacity: '60,474',
  },
  {
    name: 'Crystal Palace',
    nick_name: 'The Palacians',
    coach: 'Roy Hodgson',
    website: 'https://www.crystalpalacefc.com',
    founded: 1980,
    stadium_name: 'Selhurst Park',
    wins: 3,
    losses: 7,
    goals: 8,
    stadium_capacity: '38,786',
  },
  {
    name: 'Norwich',
    nick_name: 'The Canaries',
    coach: 'David Burke',
    website: 'https://www.norwichcityfc.com',
    founded: 1968,
    stadium_name: 'Carrow Road',
    wins: 4,
    losses: 6,
    goals: 11,
    stadium_capacity: '29,450',
  },
  {
    name: 'Southampton',
    nick_name: 'The Saints',
    coach: 'Julian Naigelsmann',
    website: 'https://www.saintsfc.com',
    founded: 1880,
    stadium_name: 'Stadium of Light',
    wins: 3,
    losses: 7,
    goals: 12,
    stadium_capacity: '31,003',
  },
  {
    name: 'Westham',
    nick_name: 'The Hammers',
    coach: 'Michel Pellegrini',
    website: 'https://www.westhamunitedfc.com',
    founded: 1998,
    stadium_name: 'London',
    wins: 4,
    losses: 6,
    goals: 10,
    stadium_capacity: '43,050',
  },
  {
    name: 'Sheffield United',
    nick_name: 'The Shefferss',
    coach: 'David Jake',
    website: 'https://www.sheffieldunitedfc.com',
    founded: 1948,
    stadium_name: 'Sheffield',
    wins: 2,
    losses: 8,
    goals: 4,
    stadium_capacity: '22,350',
  },
  {
    name: 'Newcastle',
    nick_name: 'The weapon',
    coach: 'New Coach',
    website: 'https://www.newcastleunitedfc.com',
    founded: 1948,
    stadium_name: 'Sheffield',
    wins: 1,
    losses: 9,
    goals: 3,
    stadium_capacity: '22,350',
  },
  {
    name: 'Watford',
    nick_name: 'The Yellow',
    coach: 'Javi Garcia',
    website: 'https://www.watfordfc.com',
    founded: 1948,
    stadium_name: 'Yellow field',
    wins: 0,
    losses: 10,
    goals: 4,
    stadium_capacity: '32,350',
  },
  {
    name: 'Wolves',
    nick_name: 'The Lions',
    coach: 'Uchedino',
    website: 'https://www.wolvesfc.com',
    founded: 1990,
    stadium_name: 'Wolverine',
    wins: 7,
    losses: 3,
    goals: 10,
    stadium_capacity: '45,043',
  },
];
